#pragma once

// Derived from glfw3.h
#define RAINBOW_MOUSE_BUTTON_1         0
#define RAINBOW_MOUSE_BUTTON_2         1
#define RAINBOW_MOUSE_BUTTON_3         2
#define RAINBOW_MOUSE_BUTTON_4         3
#define RAINBOW_MOUSE_BUTTON_5         4
#define RAINBOW_MOUSE_BUTTON_6         5
#define RAINBOW_MOUSE_BUTTON_7         6
#define RAINBOW_MOUSE_BUTTON_8         7
#define RAINBOW_MOUSE_BUTTON_LAST      RAINBOW_MOUSE_BUTTON_8
#define RAINBOW_MOUSE_BUTTON_LEFT      RAINBOW_MOUSE_BUTTON_1
#define RAINBOW_MOUSE_BUTTON_RIGHT     RAINBOW_MOUSE_BUTTON_2
#define RAINBOW_MOUSE_BUTTON_MIDDLE    RAINBOW_MOUSE_BUTTON_3